version: '3.7'
services:
  gatsby:
    build:
      context: .
      dockerfile: gatsby.Dockerfile
    working_dir: /app/
    command: ./docker-entrypoint.sh
    ports:
      - "8888:8888"
    volumes:
     - .:/app
     - /app/node_modules/
